# Site settings
title          : CMP
title_long     : Crossmedia Publishing
copyright_year : 2015-2016
copyright_owner: Arteveldehogeschool
colour         : primary
language       : nl
baseurl        : "/cmp" # the subpath of your site, e.g. /blog/
course_platform: http://chamilo.arteveldehs.be/index.php?application=weblcms&go=course_viewer&course=7597
hipchat_invite : https://www.hipchat.com/g80xXuczp
hipchat_room   : https://mmp-prodev.hipchat.com/chat/room/1668988

# Build settings
highlighter: pygments
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: pygments
gems:
  - jemoji
sass:
  style: compressed