# Site settings
title          : CMP
title_long     : Crossmedia Publishing
copyright_year : 2015-2016
copyright_owner: Arteveldehogeschool
colour         : primary
language       : nl
baseurl        : "/cmp" # the subpath of your site, e.g. /blog/
course_id      : "7597"


# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
gems:
  - jemoji
sass:
  style: compressed